// 数学Ⅲ: 積分法
const qa_数学Ⅲ_積分法 = [
  ["\\(\\displaystyle \\int \\frac{1}{x}\\,dx\\) =", "\\(\\ln|x|+C\\)"],
  ["\\(\\displaystyle \\int e^x\\,dx\\) =", "\\(e^x+C\\)"],
  ["\\(\\displaystyle \\int a^x\\,dx\\) =", "\\(\\frac{a^x}{\\ln a}+C\\)"],
  ["\\(\\displaystyle \\int \\sin x\\,dx\\) =", "\\(-\\cos x+C\\)"],
  ["\\(\\displaystyle \\int \\cos x\\,dx\\) =", "\\(\\sin x+C\\)"],
  ["\\(\\displaystyle \\int \\frac{1}{\\cos^2 x}\\,dx\\) =", "\\(\\tan x+C\\)"],
  ["\\(\\displaystyle \\int \\frac{1}{1+x^2}\\,dx\\) =", "\\(\\arctan x+C\\)"],
  ["\\(\\displaystyle \\int_0^1 xe^{x^2}\\,dx\\) =", "\\(\\displaystyle \\frac12\\int_0^1e^u\\,du=\\frac{e-1}{2}\\)"],
  ["\\(\\displaystyle\\int x^n\\,dx\\quad(n\\ne-1)\\)","\\(\\displaystyle \\dfrac{x^{n+1}}{n+1}+C\\)"],
  ["\\(\\displaystyle\\int \\dfrac1x\\,dx\\)","\\(\\log|x|+C\\)"],
  ["\\(\\displaystyle\\int e^x\\,dx\\)","\\(e^x+C\\)"],
  ["\\(\\displaystyle\\int \\sin x\\,dx\\)","\\(-\\cos x+C\\)"],
  ["\\(\\displaystyle\\int \\cos x\\,dx\\)","\\(\\sin x+C\\)"],
  ["\\(\\displaystyle\\int_0^1 2xe^{x^2}\\,dx\\)","\\(\\displaystyle =\\int_0^1 e^u\\,du=e-1\\)"],
  ["\\(\\displaystyle\\int x\\cos x\\,dx\\)","\\(\\displaystyle =x\\sin x-\\int\\sin x\\,dx\n=x\\sin x+\\cos x+C\\)"],
  ["\\(\\displaystyle\\int x e^x\\,dx\\)","\\(\\displaystyle =xe^x-\\int e^x\\,dx\n=e^x(x-1)+C\\)"],
  ["\\(\\displaystyle\\int_0^\\pi x\\sin x\\,dx\\)","\\(\\displaystyle =[-x\\cos x]_0^\\pi+\\int_0^\\pi\\cos x\\,dx\n=\\pi\\)"],
  ["\\(\\displaystyle\\int_0^1 \\dfrac{2x}{1+x^2}\\,dx\\)","\\(\\displaystyle =\\int_1^2\\dfrac1u\\,du=\\log2\\)"],
  ["\\(\\displaystyle\\int_0^1 \\dfrac1{1+x^2}\\,dx\\)","\\(\\displaystyle =\\arctan1-\\arctan0=\\dfrac\\pi4\\)"],
  ["\\(\\displaystyle\\int_0^{\\pi/3}\\tan x\\,dx\\)","\\(\\displaystyle =[-\\log\\cos x]_0^{\\pi/3}=\\log2\\)"],
];
