// 数学Ⅲ: 極限
const qa_数学Ⅲ_極限 = [
  ["\\(\\displaystyle \\lim_{x\\to1}\\frac{x^2-1}{x-1}\\) を求めよ。", "\\(x^2-1=(x-1)(x+1)\\) より\n\\(\\displaystyle \\frac{x^2-1}{x-1}=x+1\\to2\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{\\sqrt{1+x}-1}{x}\\) を求めよ。", "分子を有理化すると \\(\\displaystyle \\frac{1}{\\sqrt{1+x}+1}\\to\\frac12\\)"],
  ["\\(\\displaystyle \\lim_{n\\to\\infty}(\\sqrt{n^2+n}-n)\\) を求めよ。", "有理化すると \\(\\displaystyle \\frac{n}{\\sqrt{n^2+n}+n}=\\frac1{\\sqrt{1+1/n}+1}\\to\\frac12\\)"],
  ["\\(\\displaystyle \\lim_{x\\to\\infty}(\\sqrt{x^2+x}-x)\\) を求めよ。", "有理化して分子・分母を \\(x\\) で割ると\n\\(\\displaystyle \\frac{x}{\\sqrt{x^2+x}+x}=\\frac1{\\sqrt{1+1/x}+1}\\to\\frac12\\)"],
  ["\\(\\displaystyle\\lim_{x\\to\\infty}x(\\sqrt{x^2+1}-x)\\) を求めよ。", "有理化すると \\(\\displaystyle\\frac{x}{\\sqrt{x^2+1}+x}=\\frac1{\\sqrt{1+1/x^2}+1}\\to\\frac12\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{|x|}{x}\\) は存在するか。", "\\(\\displaystyle \\lim_{x\\to0+}\\frac{|x|}{x}=1,\\qquad \\lim_{x\\to0-}\\frac{|x|}{x}=-1\\)\n左右の極限が異なるので、極限は存在しない"],
  ["\\(\\displaystyle \\lim_{x\\to0+}\\frac1x\\) を求めよ。", "\\(x\\to0+\\) では \\(x>0\\) のまま分母が \\(0\\) に近づくので\n\\(\\displaystyle \\frac1x\\to+\\infty\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}x\\sin\\frac1x\\) を求めよ。", "\\(\\displaystyle \\left|x\\sin\\frac1x\\right|\\le|x|\\to0\\)\nはさみうちの原理より \\(0\\)"],
  ["\\(\\displaystyle \\lim_{x\\to\\infty}\\frac{\\sin x}{x}\\) を求めよ。", "\\(\\displaystyle \\left|\\frac{\\sin x}{x}\\right|\\le\\frac1x\\to0\\)\\nはさみうちの原理より \\(0\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{\\sin x}{x}\\) を求めよ。", "\\(\\displaystyle \\cos x\\le\\frac{\\sin x}{x}\\le1\\) と \\(\\cos x\\to1\\) より\nはさみうちの原理から \\(\\displaystyle 1\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{\\sin3x}{x}\\) を求めよ。", "\\(\\displaystyle \\frac{\\sin3x}{x}=3\\frac{\\sin3x}{3x}\\)\n\\(\\displaystyle \\therefore 3\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{\\tan x}{x}\\) を求めよ。", "\\(\\displaystyle \\frac{\\tan x}{x}=\\frac{\\sin x}{x}\\cdot\\frac1{\\cos x}\\)\n\\(\\displaystyle \\therefore 1\\cdot1=1\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{1-\\cos x}{x^2}\\) を求めよ。", "\\(\\displaystyle \\frac{1-\\cos x}{x^2}=\\frac{2\\sin^2(x/2)}{x^2}=\\frac12\\left(\\frac{\\sin(x/2)}{x/2}\\right)^2\\)\n\\(\\displaystyle \\therefore \\frac12\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{1-\\cos2x}{x^2}\\) を求めよ。", "\\(1-\\cos2x=2\\sin^2x\\) より\n\\(\\displaystyle \\frac{1-\\cos2x}{x^2}=2\\left(\\frac{\\sin x}{x}\\right)^2\\to2\\)"],
  ["\\(\\displaystyle\\lim_{x\\to0}\\frac{\\log(\\cos x)}{x^2}\\) を求めよ。", "\\(\\displaystyle\\frac{\\log(\\cos x)}{x^2}=\\frac{\\log(1+u)}u\\cdot\\frac{\\cos x-1}{x^2}\\), \\(u=\\cos x-1\\) とおく。前者は \\(1\\)、後者は \\(-1/2\\) に収束するので \\(-1/2\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{e^x-1}{x}\\) を求めよ。", "\\(t=e^x-1\\) とおくと \\(x=\\log(1+t)\\)\n\\(t\\to0\\) のとき\n\\(\\displaystyle \\frac{e^x-1}{x}=\\frac{t}{\\log(1+t)}\\to1\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{e^{2x}-1}{x}\\) を求めよ。", "\\(u=2x\\) とおくと\n\\(\\displaystyle \\frac{e^{2x}-1}{x}=2\\frac{e^u-1}{u}\\to2\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{2^x-1}{x}\\) を求めよ。", "\\(2^x=e^{x\\log2}\\)、\\(u=x\\log2\\) とおくと\n\\(\\displaystyle \\frac{2^x-1}{x}=\\log2\\,\\frac{e^u-1}{u}\\to\\log2\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}\\frac{\\log(1+3x)}{x}\\) を求めよ。", "\\(u=3x\\) とおくと\n\\(\\displaystyle \\frac{\\log(1+3x)}x=3\\frac{\\log(1+u)}u\\to3\\)"],
  ["\\(\\displaystyle \\lim_{x\\to0}(1+x)^{1/x}\\) を求めよ。", "\\(y=(1+x)^{1/x}\\) とおくと\n\\(\\displaystyle \\log y=\\frac{\\log(1+x)}x\\to1\\) より\n\\(y\\to e\\)"],
  ["\\(\\displaystyle \\lim_{n\\to\\infty}\\left(1+\\frac{1}{n}\\right)^n\\) を求めよ。", "\\(a_n=\\left(1+\\frac1n\\right)^n\\) とおくと\n\\(\\displaystyle \\log a_n=\\frac{\\log(1+1/n)}{1/n}\\to1\\) より、\\(a_n\\to e\\)"],
  ["\\(\\displaystyle \\lim_{n\\to\\infty}\\left(1+\\frac3n\\right)^n\\) を求めよ。", "\\(\\displaystyle \\left(1+\\frac3n\\right)^n=\\left\\{\\left(1+\\frac3n\\right)^{n/3}\\right\\}^3\\)\n括弧内は \\(e\\) に収束するので、極限は \\(e^3\\)"],
  ["\\(\\displaystyle \\lim_{n\\to\\infty}n^{1/n}\\) を求めよ。", "\\(a_n=n^{1/n}\\) とおくと\n\\(\\displaystyle \\log a_n=\\frac{\\log n}{n}\\to0\\) より、\\(a_n\\to e^0=1\\)"],
  ["\\(\\displaystyle \\lim_{x\\to\\infty}\\frac{\\log x}{x}\\) を求めよ。", "\\(x=e^t\\) とおくと \\(t\\to\\infty\\) で、\\(\\displaystyle \\frac{\\log x}{x}=\\frac{t}{e^t}\\)\n\\(e^t\\ge t^2/2\\) より\n\\(0\\le t/e^t\\le2/t\\to0\\)"],
  ["\\(a_1=\\sqrt2,\\ a_{n+1}=\\sqrt{2+a_n}\\) で定める数列の極限を求めよ。", "\\(0<a_n<2\\) では \\(a_{n+1}>a_n\\) で、上に \\(2\\) を上界にもつから収束する。極限を \\(L\\ge0\\) とすると \\(L=\\sqrt{2+L}\\)、よって \\(L=2\\)"],
  ["\\(|r|<1\\) のとき、無限等比級数 \\(\\displaystyle S = \\sum_{n=0}^{\\infty}r^n\\) の和を求めよ。", "\\(\\displaystyle S_N =\\frac{1-r^{N+1}}{1-r}\\)\n\\(r^{N+1}\\to0\\) より\n\\(\\displaystyle S=\\frac{1}{1-r}\\)"],
  ["\\(\\displaystyle \\sum_{n=1}^{\\infty}\\frac1{n(n+1)}\\) の和を求めよ。", "\\(\\displaystyle \\frac1{n(n+1)}=\\frac1n-\\frac1{n+1}\\) より\n\\(\\displaystyle 1-\\frac1{N+1}\\to1\\)"],
  ["無限級数 \\(\\displaystyle\\sum_{n=1}^{\\infty}\\frac1{n(n+2)}\\) の和を求めよ。", "\\(\\dfrac1{n(n+2)}=\\dfrac12\\left(\\dfrac1n-\\dfrac1{n+2}\\right)\\)。部分和をとると途中が消え、極限は \\(\\dfrac12\\left(1+\\dfrac12\\right)=\\dfrac34\\)"],
  ["\\(\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=0}^{n}\\frac{n^k}{n^n}\\) を求めよ。", "等比数列の和より \\(\\displaystyle\\sum_{k=0}^{n}\\frac{n^k}{n^n}=\\frac{n^{n+1}-1}{n^n(n-1)}=\\frac{n-n^{-n}}{n-1}\\to1\\)"]
];
