// 数学Ⅱ: 三角関数
const qa_数学Ⅱ_三角関数 = [
  ["\\(\\sin\\frac{\\pi}{6}\\) =", "\\(\\frac{1}{2}\\)"],
  ["\\(\\cos\\frac{\\pi}{6}\\) =", "\\(\\frac{\\sqrt3}{2}\\)"],
  ["\\(\\sin\\frac{\\pi}{3}\\) =", "\\(\\frac{\\sqrt3}{2}\\)"],
  ["\\(\\cos\\frac{\\pi}{3}\\) =", "\\(\\frac{1}{2}\\)"],
  ["\\(\\tan\\frac{\\pi}{6}\\) =", "\\(\\frac{1}{\\sqrt3}\\)"],
  ["\\(\\tan\\frac{\\pi}{4}\\) =", "\\(1\\)"],
  ["\\(\\sin^2 x+\\cos^2 x\\) =", "\\(1\\)"],
  ["\\(1+\\tan^2 x\\) =", "\\(\\frac{1}{\\cos^2 x}\\)"],
  ["\\(\\sin(\\alpha+\\beta)\\) =", "\\(\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta\\)"],
  ["\\(\\cos(\\alpha+\\beta)\\) =", "\\(\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta\\)"],
  ["\\(\\tan(\\alpha+\\beta)\\) =", "\\(\\displaystyle \\frac{\\tan\\alpha+\\tan\\beta}{1-\\tan\\alpha\\tan\\beta}\\)"],
  ["\\(\\sin2x\\) =", "\\(2\\sin x\\cos x\\)"],
  ["\\(\\cos2x\\) =", "\\(\\cos^2 x-\\sin^2 x\\)"],
  ["\\(\\cos2\\theta\\text{ を }\\cos\\theta\\text{ だけで表せ}\\)", "\\(\\cos2\\theta=2\\cos^2\\theta-1\\)"],
  ["\\(\\cos2\\theta\\text{ を }\\sin\\theta\\text{ だけで表せ}\\)", "\\(\\cos2\\theta=1-2\\sin^2\\theta\\)"],
  ["\\(\\tan2x\\) =", "\\(\\frac{2\\tan x}{1-\\tan^2 x}\\)"],
  ["\\(\\displaystyle \\tan2\\theta\\)", "\\(\\displaystyle =\\dfrac{2\\tan\\theta}{1-\\tan^2\\theta}\\)"],
  ["\\(\\displaystyle \\sin^2\\dfrac\\theta2\\)", "\\(\\displaystyle =\\dfrac{1-\\cos\\theta}{2}\\)"],
  ["\\(\\displaystyle \\cos^2\\dfrac\\theta2\\)", "\\(\\displaystyle =\\dfrac{1+\\cos\\theta}{2}\\)"],
  ["\\(\\displaystyle \\tan^2\\dfrac\\theta2\\)", "\\(\\displaystyle =\\dfrac{1-\\cos\\theta}{1+\\cos\\theta}\\)"],
  ["\\(\\sin 3\\theta\\) =", "\\(3\\sin\\theta-4\\sin^3\\theta\\)"],
  ["\\(\\sin3\\theta\\text{ を }\\sin\\theta\\text{ で表せ}\\)", "\\(\\sin3\\theta=3\\sin\\theta-4\\sin^3\\theta\\)"],
  ["\\(\\cos3\\theta\\text{ を }\\cos\\theta\\text{ で表せ}\\)", "\\(\\cos3\\theta=4\\cos^3\\theta-3\\cos\\theta\\)"],
  ["\\(\\displaystyle \\tan3\\theta\\)", "\\(\\displaystyle =\\dfrac{3\\tan\\theta-\\tan^3\\theta}{1-3\\tan^2\\theta}\\)"],
  ["\\(\\sin A+\\sin B\\text{ を積の形にせよ}\\)", "\\(\\displaystyle \\sin A+\\sin B=2\\sin\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}\\)"],
  ["\\(\\cos A+\\cos B\\text{ を積の形にせよ}\\)", "\\(\\displaystyle \\cos A+\\cos B=2\\cos\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}\\)"],
  ["\\(\\cos A-\\cos B\\text{ を積の形にせよ}\\)", "\\(\\displaystyle \\cos A-\\cos B=-2\\sin\\dfrac{A+B}{2}\\sin\\dfrac{A-B}{2}\\)"],
  ["\\(\\sin A\\sin B\\) を和の形に変形せよ。", "積和公式より \\(\\sin A\\sin B=\\dfrac{\\cos(A-B)-\\cos(A+B)}2\\)"],
  ["\\(\\displaystyle \\sin^2x+\\sin^2\\left(x+\\frac{\\pi}{3}\\right)+\\sin^2\\left(x+\\frac{2\\pi}{3}\\right)\\) を簡単にすると？", "\\(\\displaystyle \\frac32\\)\n\\(\\because \\sin^2t=\\frac{1-\\cos2t}{2}\\)"],
  ["\\(\\displaystyle\\sin x\\sin\\left(x+\\frac\\pi3\\right)\\sin\\left(x+\\frac{2\\pi}3\\right)\\) を簡単にせよ。", "後ろ2因子の積は \\(\\dfrac{\\cos(-\\pi/3)-\\cos(2x+\\pi)}2=\\dfrac14+\\dfrac12\\cos2x\\)。これに \\(\\sin x\\) を掛けると \\(\\dfrac{3\\sin x-4\\sin^3x}{4}=\\dfrac{\\sin3x}{4}\\)"],
  ["\\(a\\sin x+b\\cos x\\) の最大値は？", "\\(\\sqrt{a^2+b^2}\\)"],
  ["\\(0\\le x\\le\\dfrac\\pi2\\) における \\(\\sin x+\\cos x\\) の最大値と最小値を求めよ。", "\\(\\sin x+\\cos x=\\sqrt2\\sin(x+\\pi/4)\\)。区間内で最大値は \\(x=\\pi/4\\) の \\(\\sqrt2\\)、最小値は両端で \\(1\\)"],
  ["\\(0\\le x<2\\pi\\) で \\(2\\sin x\\cos x=\\dfrac12\\) を解け。", "\\(\\sin2x=\\dfrac12\\) より \\(2x=\\dfrac\\pi6,\\dfrac{5\\pi}6\\pmod{2\\pi}\\)。したがって \\(x=\\dfrac\\pi{12},\\dfrac{5\\pi}{12},\\dfrac{13\\pi}{12},\\dfrac{17\\pi}{12}\\)"],
  ["\\(0\\le x<2\\pi\\) で \\(\\cos2x=\\sin x\\) を解け。", "\\(1-2\\sin^2x=\\sin x\\) より \\((2\\sin x-1)(\\sin x+1)=0\\)。したがって \\(x=\\dfrac\\pi6,\\dfrac{5\\pi}6,\\dfrac{3\\pi}2\\)"]
];
