// 数学Ⅲ: 微分法
const qa_数学Ⅲ_微分法 = [
  ["\\((\\sin x)' =\\)", "\\(\\cos x\\)"],
  ["\\((\\cos x)' =\\)", "\\(-\\sin x\\)"],
  ["\\((\\tan x)' =\\)", "\\(\\frac{1}{\\cos^2 x}\\)"],
  ["\\((e^x)' =\\)", "\\(e^x\\)"],
  ["\\(a>0,a\\ne1\\) のとき \\((a^x)' =\\)", "\\(a^x\\ln a\\)"],
  ["\\((\\ln x)' =\\)", "\\(\\frac{1}{x}\\)"],
  ["\\((\\log_a x)' =\\)", "\\(\\frac{1}{x\\ln a}\\)"],
  ["\\((uv)' =\\)", "\\(u'v+uv'\\)"],
  ["\\((f(g(x)))' =\\)", "\\(f'(g(x))g'(x)\\)"],
  ["\\(x>0\\) のとき、\\(y=x^x\\) の導関数は？", "\\(\\log y=x\\log x\\) の両辺を微分すると\n\\(y'=x^x(\\log x+1)\\)"],
  ["\\(\\displaystyle {d\\over dx}x^n\\)","\\(nx^{n-1}\\)"],
  ["\\(\\displaystyle {d\\over dx}\\sin x\\)","\\(\\cos x\\)"],
  ["\\(\\displaystyle {d\\over dx}\\cos x\\)","\\(-\\sin x\\)"],
  ["\\(\\displaystyle {d\\over dx}\\tan x\\)","\\(\\displaystyle \\dfrac1{\\cos^2x}=1+\\tan^2x\\)"],
  ["\\(\\displaystyle {d\\over dx}e^x\\)","\\(e^x\\)"],
  ["\\(\\displaystyle {d\\over dx}\\log x\\)","\\(\\displaystyle \\dfrac1x\\)"],
  ["\\(\\displaystyle {d\\over dx}\\log_a x\\)","\\(\\displaystyle \\log_a x=\\dfrac{\\log x}{\\log a}\\text{ より }\\dfrac1{x\\log a}\\)"],
  ["\\(\\displaystyle {d\\over dx}a^x\\)","\\(\\displaystyle a^x=e^{x\\log a}\\text{ より }a^x\\log a\\)"],
  ["\\(\\displaystyle {d\\over dx}x^x\\quad(x>0)\\)","\\(\\log y=x\\log x\\text{ とおく}\n\\therefore y'=x^x(\\log x+1)\\)"],
  ["\\(\\displaystyle {d\\over dx}\\sin x^2\\)","\\(2x\\cos x^2\\)"],
  ["\\(\\displaystyle {d\\over dx}\\log(1+x^2)\\)","\\(\\displaystyle \\dfrac{2x}{1+x^2}\\)"],
  ["\\(\\displaystyle {d\\over dx}e^{x^2}\\)","\\(2xe^{x^2}\\)"],
];
