// 数学Ⅱ: 三角関数
const qa_数学Ⅱ_三角関数 = [
  ["\\(\\sin^2 x+\\cos^2 x\\) =", "\\(1\\)"],
  ["\\(1+\\tan^2 x\\) =", "\\(\\frac{1}{\\cos^2 x}\\)"],
  ["\\(\\sin(\\alpha+\\beta)\\) =", "\\(\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta\\)"],
  ["\\(\\cos(\\alpha+\\beta)\\) =", "\\(\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta\\)"],
  ["\\(\\sin2x\\) =", "\\(2\\sin x\\cos x\\)"],
  ["\\(\\cos2x\\) =", "\\(\\cos^2 x-\\sin^2 x\\)"],
  ["\\(\\tan2x\\) =", "\\(\\frac{2\\tan x}{1-\\tan^2 x}\\)"],
  ["\\(\\sin\\frac{\\pi}{6}\\) =", "\\(\\frac{1}{2}\\)"],
  ["\\(\\cos\\frac{\\pi}{3}\\) =", "\\(\\frac{1}{2}\\)"],
  ["\\(\\tan\\frac{\\pi}{4}\\) =", "\\(1\\)"],
  ["\\(\\sin\\frac{\\pi}{3}\\) =", "\\(\\frac{\\sqrt3}{2}\\)"],
  ["\\(\\cos\\frac{\\pi}{6}\\) =", "\\(\\frac{\\sqrt3}{2}\\)"],
  ["\\(\\tan\\frac{\\pi}{6}\\) =", "\\(\\frac{1}{\\sqrt3}\\)"],
  ["\\(\\tan(\\alpha+\\beta)\\) =", "\\(\\displaystyle \\frac{\\tan\\alpha+\\tan\\beta}{1-\\tan\\alpha\\tan\\beta}\\)"],
  ["\\(\\sin 3\\theta\\) =", "\\(3\\sin\\theta-4\\sin^3\\theta\\)"],
  ["\\(a\\sin x+b\\cos x\\) の最大値は？", "\\(\\sqrt{a^2+b^2}\\)"],
  ["\\(\\displaystyle \\sin^2x+\\sin^2\\left(x+\\frac{\\pi}{3}\\right)+\\sin^2\\left(x+\\frac{2\\pi}{3}\\right)\\) を簡単にすると？", "\\(\\displaystyle \\frac32\\)\n\\(\\because \\sin^2t=\\frac{1-\\cos2t}{2}\\)"],
  ["\\(\\cos2\\theta\\text{ を }\\cos\\theta\\text{ だけで表せ}\\)","\\(\\cos2\\theta=2\\cos^2\\theta-1\\)"],
  ["\\(\\cos2\\theta\\text{ を }\\sin\\theta\\text{ だけで表せ}\\)","\\(\\cos2\\theta=1-2\\sin^2\\theta\\)"],
  ["\\(\\displaystyle \\tan2\\theta\\)","\\(\\displaystyle =\\dfrac{2\\tan\\theta}{1-\\tan^2\\theta}\\)"],
  ["\\(\\displaystyle \\sin^2\\dfrac\\theta2\\)","\\(\\displaystyle =\\dfrac{1-\\cos\\theta}{2}\\)"],
  ["\\(\\displaystyle \\cos^2\\dfrac\\theta2\\)","\\(\\displaystyle =\\dfrac{1+\\cos\\theta}{2}\\)"],
  ["\\(\\displaystyle \\tan^2\\dfrac\\theta2\\)","\\(\\displaystyle =\\dfrac{1-\\cos\\theta}{1+\\cos\\theta}\\)"],
  ["\\(\\sin3\\theta\\text{ を }\\sin\\theta\\text{ で表せ}\\)","\\(\\sin3\\theta=3\\sin\\theta-4\\sin^3\\theta\\)"],
  ["\\(\\cos3\\theta\\text{ を }\\cos\\theta\\text{ で表せ}\\)","\\(\\cos3\\theta=4\\cos^3\\theta-3\\cos\\theta\\)"],
  ["\\(\\displaystyle \\tan3\\theta\\)","\\(\\displaystyle =\\dfrac{3\\tan\\theta-\\tan^3\\theta}{1-3\\tan^2\\theta}\\)"],
  ["\\(\\sin A+\\sin B\\text{ を積の形にせよ}\\)","\\(\\displaystyle \\sin A+\\sin B=2\\sin\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}\\)"],
  ["\\(\\cos A+\\cos B\\text{ を積の形にせよ}\\)","\\(\\displaystyle \\cos A+\\cos B=2\\cos\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}\\)"],
  ["\\(\\cos A-\\cos B\\text{ を積の形にせよ}\\)","\\(\\displaystyle \\cos A-\\cos B=-2\\sin\\dfrac{A+B}{2}\\sin\\dfrac{A-B}{2}\\)"],
];
