const files_enExamples = [
  ["astronomy", 10],
  ["geography", 10],
  ["science", 10],
  ["electromagnetism", 10],
  ["color", 1],
  ["emotion", 1],
  ["existence", 1],
  ["food", 1],
  ["importance", 1],
  ["medical", 1],
  ["nature", 1],
  ["psych", 1],
  ["quantity_degrees", 1],
];