const qa_英語_重要例文和訳 = [
  ["It is essential that we take action immediately.\n日本語訳は?", "私たちが直ちに行動を起こすことが不可欠だ"],
  ["There is no doubt that she is qualified for the job.\n日本語訳は?", "彼女がその仕事に適任であることは疑いない"],
  ["The plan was abandoned due to a lack of funds.\n日本語訳は?", "その計画は資金不足のため断念された"],
  ["We should take into account the possible risks.\n日本語訳は?", "私たちは起こりうる危険を考慮に入れるべきだ"],
  ["She was absorbed in reading the novel.\n日本語訳は?", "彼女はその小説を読むことに夢中だった"],
  ["The new policy had a significant impact on the economy.\n日本語訳は?", "その新しい政策は経済に大きな影響を与えた"],
  ["He failed to live up to our expectations.\n日本語訳は?", "彼は私たちの期待に応えられなかった"],
  ["It occurred to me that I had left my wallet at home.\n日本語訳は?", "家に財布を忘れたことに気づいた"],
  ["The issue remains unresolved despite long discussions.\n日本語訳は?", "長い議論にもかかわらず、その問題は未解決のままだ"],
  ["She objected to the proposal on ethical grounds.\n日本語訳は?", "彼女は倫理的な理由でその提案に反対した"],
  ["The evidence is sufficient to support the claim.\n日本語訳は?", "その証拠は主張を裏付けるのに十分だ"],
  ["He took responsibility for the failure of the project.\n日本語訳は?", "彼はそのプロジェクトの失敗の責任を取った"],
  ["This device is designed to reduce energy consumption.\n日本語訳は?", "この装置はエネルギー消費を減らすよう設計されている"],
  ["We must rely on accurate data to draw conclusions.\n日本語訳は?", "結論を導くには正確なデータに頼らなければならない"],
  ["Her argument was so convincing that no one objected.\n日本語訳は?", "彼女の主張は非常に説得力があり、誰も反対しなかった"],
  ["He is eager to acquire new skills.\n日本語訳は?", "彼は新しい技能を身につけることに熱心だ"],
  ["The results vary depending on the conditions.\n日本語訳は?", "結果は条件によって異なる"],
  ["She made an effort to adapt herself to the new environment.\n日本語訳は?", "彼女は新しい環境に適応しようと努力した"],
  ["This problem cannot be solved without external support.\n日本語訳は?", "この問題は外部の支援なしには解決できない"],
  ["He pointed out several flaws in the argument.\n日本語訳は?", "彼はいくつかの論理的欠陥を指摘した"],
  ["The company aims to expand its business overseas.\n日本語訳は?", "その会社は海外に事業を拡大することを目指している"],
  ["She was reluctant to reveal the truth.\n日本語訳は?", "彼女は真実を明かすことに気が進まなかった"],
  ["The survey was conducted among university students.\n日本語訳は?", "その調査は大学生を対象に行われた"],
  ["We are faced with a serious environmental crisis.\n日本語訳は?", "私たちは深刻な環境危機に直面している"],
  ["The decision will have long-term consequences.\n日本語訳は?", "その決定は長期的な影響を及ぼすだろう"],
  ["It is up to you to decide.\n日本語訳は?", "決めるのはあなた次第だ"],
  ["She took it for granted that he would help her.\n日本語訳は?", "彼が助けてくれるのを当然だと思っていた"],
  ["The meeting was postponed until next week.\n日本語訳は?", "会議は来週まで延期された"],
  ["We are running out of water.\n日本語訳は?", "水がなくなってきている"],
  ["Please let me know as soon as possible.\n日本語訳は?", "できるだけ早く知らせてください"],
  ["He insisted on going there alone.\n日本語訳は?", "彼は一人でそこへ行くと言い張った"],
  ["She is capable of solving the problem on her own.\n日本語訳は?", "彼女は自力でその問題を解く能力がある"],
  ["I was disappointed to hear the news.\n日本語訳は?", "その知らせを聞いてがっかりした"],
  ["The more you practice, the better you become.\n日本語訳は?", "練習すればするほど上達する"],
  ["It was not until I met him that I understood the truth.\n日本語訳は?", "彼に会って初めて真実が分かった"],
  ["Not only did he apologize,\nbut he also offered compensation.\n日本語訳は?", "彼は謝罪しただけでなく、補償も申し出た"],
  ["Hardly had I arrived when it started to rain.\n日本語訳は?", "到着するやいなや雨が降り出した"],
  ["If I had known, I would have told you.\n日本語訳は?", "知っていたらあなたに伝えていただろう"],
  ["She would rather stay home than go out.\n日本語訳は?", "彼女は外出するより家にいたい"],
  ["All you have to do is press this button.\n日本語訳は?", "このボタンを押しさえすればいい"],
  ["It makes no difference to me.\n日本語訳は?", "私にはどちらでも同じだ"],
  ["He was accused of stealing money.\n日本語訳は?", "彼は金を盗んだと非難された"],
  ["The patient is recovering from the operation.\n日本語訳は?", "患者は手術から回復しつつある"],
  ["The product is available at most stores.\n日本語訳は?", "その製品はほとんどの店で手に入る"],
  ["She was promoted to manager last year.\n日本語訳は?", "彼女は昨年マネージャーに昇進した"],
  ["The museum is closed on Mondays.\n日本語訳は?", "その博物館は月曜休館だ"],
  ["He devoted himself to studying medicine.\n日本語訳は?", "彼は医学の勉強に専念した"],
  ["The data was collected from various sources.\n日本語訳は?", "そのデータはさまざまな情報源から集められた"],
  ["It is likely that prices will rise.\n日本語訳は?", "物価が上がる可能性が高い"],
  ["She was aware of the danger.\n日本語訳は?", "彼女は危険に気づいていた"],
  ["We should make the most of our limited time.\n日本語訳は?", "限られた時間を最大限に活用すべきだ"],
  ["He made a point of arriving on time.\n日本語訳は?", "彼は時間通りに来ることを心がけた"],
  ["The accident was caused by human error.\n日本語訳は?", "その事故は人為的ミスが原因だった"],
  ["She is responsible for customer support.\n日本語訳は?", "彼女は顧客対応を担当している"],
  ["I am not satisfied with the result.\n日本語訳は?", "その結果には満足していない"],
  ["The company went bankrupt last month.\n日本語訳は?", "その会社は先月倒産した"],
  ["He was reluctant to admit his mistake.\n日本語訳は?", "彼は自分の誤りを認めたがらなかった"],
  ["The project is still in progress.\n日本語訳は?", "そのプロジェクトはまだ進行中だ"],
  ["We need to figure out what went wrong.\n日本語訳は?", "何が悪かったのか突き止める必要がある"],
  ["He is supposed to submit the report by Friday.\n日本語訳は?", "彼は金曜までに報告書を提出することになっている"],
  ["She is looking forward to meeting you.\n日本語訳は?", "彼女はあなたに会うのを楽しみにしている"],
  ["The rumor turned out to be true.\n日本語訳は?", "そのうわさは本当だと分かった"],
  ["He finally managed to solve the puzzle.\n日本語訳は?", "彼はついにそのパズルを解くことに成功した"],
  ["She apologized for being late.\n日本語訳は?", "彼女は遅れたことを謝った"],
  ["The train was delayed because of an accident.\n日本語訳は?", "事故のため電車は遅れた"],
  ["You are free to use this information.\n日本語訳は?", "この情報は自由に使ってよい"],
  ["To be honest, I don't agree with him.\n日本語訳は?", "正直言って、私は彼に賛成しない"],
  ["It depends on how you look at it.\n日本語訳は?", "見方による"],
  ["He has a strong influence on his students.\n日本語訳は?", "彼は生徒に強い影響を与える"],
  ["The government introduced new regulations.\n日本語訳は?", "政府は新しい規制を導入した"],
  ["The store offers a wide variety of products.\n日本語訳は?", "その店は幅広い商品を扱っている"],
  ["I would like to make a reservation.\n日本語訳は?", "予約したいのですが"],
  ["She was forced to resign from her position.\n日本語訳は?", "彼女はその職を辞めざるを得なかった"],
  ["We should focus on what we can do now.\n日本語訳は?", "今できることに集中すべきだ"],
  ["He is likely to be late because of the traffic.\n日本語訳は?", "渋滞で彼は遅れそうだ"],
  ["The evidence points to his innocence.\n日本語訳は?", "証拠は彼の無実を示している"],
  ["She made up her mind to study abroad.\n日本語訳は?", "彼女は留学する決心をした"],
  ["I was impressed by his presentation.\n日本語訳は?", "彼の発表に感心した"],
  ["We should refrain from making hasty judgments.\n日本語訳は?", "早まった判断は控えるべきだ"],
  ["The research sheds light on the cause of the disease.\n日本語訳は?", "その研究は病気の原因を明らかにしている"],
  ["The proposal was rejected by the committee.\n日本語訳は?", "その提案は委員会に却下された"],
  ["I am willing to take on the challenge.\n日本語訳は?", "その挑戦を引き受けるつもりだ"],
  ["She has a tendency to exaggerate.\n日本語訳は?", "彼女は大げさに言う傾向がある"],
  ["He was on the verge of giving up.\n日本語訳は?", "彼は諦めかけていた"],
  ["The company is undergoing major changes.\n日本語訳は?", "その会社は大きな変革の最中だ"],
  ["The book is worth reading.\n日本語訳は?", "その本は読む価値がある"],
  ["She provided him with practical advice.\n日本語訳は?", "彼女は彼に実用的な助言をした"],
  ["He is said to have invented the device.\n日本語訳は?", "彼がその装置を発明したと言われている"],
  ["The stadium can accommodate fifty thousand people.\n日本語訳は?", "そのスタジアムは5万人収容できる"],
  ["They reached an agreement after negotiations.\n日本語訳は?", "交渉の末、合意に達した"],
  ["He is engaged in environmental research.\n日本語訳は?", "彼は環境研究に従事している"],
  ["The experiment was carried out under strict conditions.\n日本語訳は?", "その実験は厳密な条件下で行われた"],
  ["In spite of the rain, we went out.\n日本語訳は?", "雨にもかかわらず、私たちは出かけた"],
  ["As a result, the sales increased rapidly.\n日本語訳は?", "その結果、売上は急増した"],
  ["On the other hand, the costs also rose.\n日本語訳は?", "一方で、費用も増えた"],
  ["He was able to overcome his fear.\n日本語訳は?", "彼は恐怖を克服できた"],
  ["We should keep in mind that mistakes happen.\n日本語訳は?", "間違いは起こりうることを心に留めるべきだ"],
  ["She is in charge of marketing.\n日本語訳は?", "彼女はマーケティング担当だ"],
  ["The medicine has side effects.\n日本語訳は?", "その薬には副作用がある"],
  ["She burst into tears when she heard the news.\n日本語訳は?", "その知らせを聞いて彼女は泣き出した"],
  ["It took me a while to get used to the new job.\n日本語訳は?", "新しい仕事に慣れるのにしばらくかかった"],
  ["He is accustomed to working under pressure.\n日本語訳は?", "彼はプレッシャーの下で働くことに慣れている"]
];
