const qa_英語例文 = [
  ["I would appreciate it if you could help me. 日本語訳は？", "助けていただけるとありがたいです。"],
  ["It is essential that we take action immediately. 日本語訳は？", "私たちが直ちに行動を起こすことが不可欠だ。"],
  ["He tends to put off important decisions. 日本語訳は？", "彼は重要な決断を先延ばしにする傾向がある。"],
  ["There is no doubt that she is qualified for the job. 日本語訳は？", "彼女がその仕事に適任であることは疑いない。"],
  ["The plan was abandoned due to a lack of funds. 日本語訳は？", "その計画は資金不足のため断念された。"],
  ["We should take into account the possible risks. 日本語訳は？", "私たちは起こりうる危険を考慮に入れるべきだ。"],
  ["This theory is based on a series of experiments. 日本語訳は？", "この理論は一連の実験に基づいている。"],
  ["She was absorbed in reading the novel. 日本語訳は？", "彼女はその小説を読むことに夢中だった。"],
  ["The new policy had a significant impact on the economy. 日本語訳は？", "その新しい政策は経済に大きな影響を与えた。"],
  ["He failed to live up to our expectations. 日本語訳は？", "彼は私たちの期待に応えられなかった。"],

  ["It occurred to me that I had left my wallet at home. 日本語訳は？", "家に財布を忘れたことに気づいた。"],
  ["The issue remains unresolved despite long discussions. 日本語訳は？", "長い議論にもかかわらず、その問題は未解決のままだ。"],
  ["She objected to the proposal on ethical grounds. 日本語訳は？", "彼女は倫理的な理由でその提案に反対した。"],
  ["The evidence is sufficient to support the claim. 日本語訳は？", "その証拠は主張を裏付けるのに十分だ。"],
  ["He took responsibility for the failure of the project. 日本語訳は？", "彼はそのプロジェクトの失敗の責任を取った。"],
  ["This device is designed to reduce energy consumption. 日本語訳は？", "この装置はエネルギー消費を減らすよう設計されている。"],
  ["We must rely on accurate data to draw conclusions. 日本語訳は？", "結論を導くには正確なデータに頼らなければならない。"],
  ["Her argument was so convincing that no one objected. 日本語訳は？", "彼女の主張は非常に説得力があり、誰も反対しなかった。"],
  ["The situation gradually got worse over time. 日本語訳は？", "状況は時間とともに徐々に悪化した。"],
  ["He is eager to acquire new skills. 日本語訳は？", "彼は新しい技能を身につけることに熱心だ。"],

  ["The results vary depending on the conditions. 日本語訳は？", "結果は条件によって異なる。"],
  ["She made an effort to adapt herself to the new environment. 日本語訳は？", "彼女は新しい環境に適応しようと努力した。"],
  ["This problem cannot be solved without external support. 日本語訳は？", "この問題は外部の支援なしには解決できない。"],
  ["He pointed out several flaws in the argument. 日本語訳は？", "彼はいくつかの論理的欠陥を指摘した。"],
  ["The company aims to expand its business overseas. 日本語訳は？", "その会社は海外に事業を拡大することを目指している。"],
  ["She was reluctant to reveal the truth. 日本語訳は？", "彼女は真実を明かすことに気が進まなかった。"],
  ["The survey was conducted among university students. 日本語訳は？", "その調査は大学生を対象に行われた。"],
  ["We are faced with a serious environmental crisis. 日本語訳は？", "私たちは深刻な環境危機に直面している。"],
  ["He eventually came to accept the reality. 日本語訳は？", "彼は最終的に現実を受け入れるようになった。"],
  ["The decision will have long-term consequences. 日本語訳は？", "その決定は長期的な影響を及ぼすだろう。"]
];