const qa_英語例文 = [
  ["I would appreciate it if you could help me. 日本語訳は？", "助けていただけるとありがたいです。"],
  ["It is essential that we take action immediately. 日本語訳は？", "私たちが直ちに行動を起こすことが不可欠だ。"],
  ["He tends to put off important decisions. 日本語訳は？", "彼は重要な決断を先延ばしにする傾向がある。"],
  ["There is no doubt that she is qualified for the job. 日本語訳は？", "彼女がその仕事に適任であることは疑いない。"],
  ["The plan was abandoned due to a lack of funds. 日本語訳は？", "その計画は資金不足のため断念された。"],
  ["We should take into account the possible risks. 日本語訳は？", "私たちは起こりうる危険を考慮に入れるべきだ。"],
  ["This theory is based on a series of experiments. 日本語訳は？", "この理論は一連の実験に基づいている。"],
  ["She was absorbed in reading the novel. 日本語訳は？", "彼女はその小説を読むことに夢中だった。"],
  ["The new policy had a significant impact on the economy. 日本語訳は？", "その新しい政策は経済に大きな影響を与えた。"],
  ["He failed to live up to our expectations. 日本語訳は？", "彼は私たちの期待に応えられなかった。"],
  ["It occurred to me that I had left my wallet at home. 日本語訳は？", "家に財布を忘れたことに気づいた。"],
  ["The issue remains unresolved despite long discussions. 日本語訳は？", "長い議論にもかかわらず、その問題は未解決のままだ。"],
  ["She objected to the proposal on ethical grounds. 日本語訳は？", "彼女は倫理的な理由でその提案に反対した。"],
  ["The evidence is sufficient to support the claim. 日本語訳は？", "その証拠は主張を裏付けるのに十分だ。"],
  ["He took responsibility for the failure of the project. 日本語訳は？", "彼はそのプロジェクトの失敗の責任を取った。"],
  ["This device is designed to reduce energy consumption. 日本語訳は？", "この装置はエネルギー消費を減らすよう設計されている。"],
  ["We must rely on accurate data to draw conclusions. 日本語訳は？", "結論を導くには正確なデータに頼らなければならない。"],
  ["Her argument was so convincing that no one objected. 日本語訳は？", "彼女の主張は非常に説得力があり、誰も反対しなかった。"],
  ["The situation gradually got worse over time. 日本語訳は？", "状況は時間とともに徐々に悪化した。"],
  ["He is eager to acquire new skills. 日本語訳は？", "彼は新しい技能を身につけることに熱心だ。"],
  ["The results vary depending on the conditions. 日本語訳は？", "結果は条件によって異なる。"],
  ["She made an effort to adapt herself to the new environment. 日本語訳は？", "彼女は新しい環境に適応しようと努力した。"],
  ["This problem cannot be solved without external support. 日本語訳は？", "この問題は外部の支援なしには解決できない。"],
  ["He pointed out several flaws in the argument. 日本語訳は？", "彼はいくつかの論理的欠陥を指摘した。"],
  ["The company aims to expand its business overseas. 日本語訳は？", "その会社は海外に事業を拡大することを目指している。"],
  ["She was reluctant to reveal the truth. 日本語訳は？", "彼女は真実を明かすことに気が進まなかった。"],
  ["The survey was conducted among university students. 日本語訳は？", "その調査は大学生を対象に行われた。"],
  ["We are faced with a serious environmental crisis. 日本語訳は？", "私たちは深刻な環境危機に直面している。"],
  ["He eventually came to accept the reality. 日本語訳は？", "彼は最終的に現実を受け入れるようになった。"],
  ["The decision will have long-term consequences. 日本語訳は？", "その決定は長期的な影響を及ぼすだろう。"],
  ["It is up to you to decide. 日本語訳は？", "決めるのはあなた次第だ。"],
  ["I cannot afford to waste time. 日本語訳は？", "時間を無駄にする余裕はない。"],
  ["She took it for granted that he would help her. 日本語訳は？", "彼が助けてくれるのを当然だと思っていた。"],
  ["The meeting was postponed until next week. 日本語訳は？", "会議は来週まで延期された。"],
  ["We are running out of water. 日本語訳は？", "水がなくなってきている。"],
  ["Please let me know as soon as possible. 日本語訳は？", "できるだけ早く知らせてください。"],
  ["He insisted on going there alone. 日本語訳は？", "彼は一人でそこへ行くと言い張った。"],
  ["She is capable of solving the problem on her own. 日本語訳は？", "彼女は自力でその問題を解く能力がある。"],
  ["I was disappointed to hear the news. 日本語訳は？", "その知らせを聞いてがっかりした。"],
  ["The more you practice, the better you become. 日本語訳は？", "練習すればするほど上達する。"],
  ["It was not until I met him that I understood the truth. 日本語訳は？", "彼に会って初めて真実が分かった。"],
  ["Not only did he apologize, but he also offered compensation. 日本語訳は？", "彼は謝罪しただけでなく、補償も申し出た。"],
  ["Hardly had I arrived when it started to rain. 日本語訳は？", "到着するやいなや雨が降り出した。"],
  ["If I had known, I would have told you. 日本語訳は？", "知っていたらあなたに伝えていただろう。"],
  ["She would rather stay home than go out. 日本語訳は？", "彼女は外出するより家にいたい。"],
  ["All you have to do is press this button. 日本語訳は？", "このボタンを押しさえすればいい。"],
  ["It makes no difference to me. 日本語訳は？", "私にはどちらでも同じだ。"],
  ["He was accused of stealing money. 日本語訳は？", "彼は金を盗んだと非難された。"],
  ["The patient is recovering from the operation. 日本語訳は？", "患者は手術から回復しつつある。"],
  ["The product is available at most stores. 日本語訳は？", "その製品はほとんどの店で手に入る。"],
  ["She was promoted to manager last year. 日本語訳は？", "彼女は昨年マネージャーに昇進した。"],
  ["The museum is closed on Mondays. 日本語訳は？", "その博物館は月曜休館だ。"],
  ["He devoted himself to studying medicine. 日本語訳は？", "彼は医学の勉強に専念した。"],
  ["The data was collected from various sources. 日本語訳は？", "そのデータはさまざまな情報源から集められた。"],
  ["It is likely that prices will rise. 日本語訳は？", "物価が上がる可能性が高い。"],
  ["She was aware of the danger. 日本語訳は？", "彼女は危険に気づいていた。"],
  ["We should make the most of our limited time. 日本語訳は？", "限られた時間を最大限に活用すべきだ。"],
  ["He made a point of arriving on time. 日本語訳は？", "彼は時間通りに来ることを心がけた。"],
  ["The accident was caused by human error. 日本語訳は？", "その事故は人為的ミスが原因だった。"],
  ["She is responsible for customer support. 日本語訳は？", "彼女は顧客対応を担当している。"],
  ["I am not satisfied with the result. 日本語訳は？", "その結果には満足していない。"],
  ["The company went bankrupt last month. 日本語訳は？", "その会社は先月倒産した。"],
  ["He was reluctant to admit his mistake. 日本語訳は？", "彼は自分の誤りを認めたがらなかった。"],
  ["The project is still in progress. 日本語訳は？", "そのプロジェクトはまだ進行中だ。"],
  ["We need to figure out what went wrong. 日本語訳は？", "何が悪かったのか突き止める必要がある。"],
  ["He is supposed to submit the report by Friday. 日本語訳は？", "彼は金曜までに報告書を提出することになっている。"],
  ["She is looking forward to meeting you. 日本語訳は？", "彼女はあなたに会うのを楽しみにしている。"],
  ["I have no choice but to accept it. 日本語訳は？", "それを受け入れるしかない。"],
  ["The rumor turned out to be true. 日本語訳は？", "そのうわさは本当だと分かった。"],
  ["We cannot ignore the fact that the population is aging. 日本語訳は？", "人口が高齢化しているという事実を無視できない。"],
  ["He finally managed to solve the puzzle. 日本語訳は？", "彼はついにそのパズルを解くことに成功した。"],
  ["She apologized for being late. 日本語訳は？", "彼女は遅れたことを謝った。"],
  ["The train was delayed because of an accident. 日本語訳は？", "事故のため電車は遅れた。"],
  ["You are free to use this information. 日本語訳は？", "この情報は自由に使ってよい。"],
  ["To be honest, I don't agree with him. 日本語訳は？", "正直言って、私は彼に賛成しない。"],
  ["It depends on how you look at it. 日本語訳は？", "見方による。"],
  ["He has a strong influence on his students. 日本語訳は？", "彼は生徒に強い影響を与える。"],
  ["The government introduced new regulations. 日本語訳は？", "政府は新しい規制を導入した。"],
  ["The store offers a wide variety of products. 日本語訳は？", "その店は幅広い商品を扱っている。"],
  ["I would like to make a reservation. 日本語訳は？", "予約したいのですが。"],
  ["She was forced to resign from her position. 日本語訳は？", "彼女はその職を辞めざるを得なかった。"],
  ["We should focus on what we can do now. 日本語訳は？", "今できることに集中すべきだ。"],
  ["He is likely to be late because of the traffic. 日本語訳は？", "渋滞で彼は遅れそうだ。"],
  ["The evidence points to his innocence. 日本語訳は？", "証拠は彼の無実を示している。"],
  ["She made up her mind to study abroad. 日本語訳は？", "彼女は留学する決心をした。"],
  ["I was impressed by his presentation. 日本語訳は？", "彼の発表に感心した。"],
  ["We should refrain from making hasty judgments. 日本語訳は？", "早まった判断は控えるべきだ。"],
  ["The research sheds light on the cause of the disease. 日本語訳は？", "その研究は病気の原因を明らかにしている。"],
  ["He is struggling to make ends meet. 日本語訳は？", "彼は生活をやりくりするのに苦労している。"],
  ["The proposal was rejected by the committee. 日本語訳は？", "その提案は委員会に却下された。"],
  ["I am willing to take on the challenge. 日本語訳は？", "その挑戦を引き受けるつもりだ。"],
  ["She has a tendency to exaggerate. 日本語訳は？", "彼女は大げさに言う傾向がある。"],
  ["He was on the verge of giving up. 日本語訳は？", "彼は諦めかけていた。"],
  ["The company is undergoing major changes. 日本語訳は？", "その会社は大きな変革の最中だ。"],
  ["It is no wonder that he is popular. 日本語訳は？", "彼が人気なのも当然だ。"],
  ["The book is worth reading. 日本語訳は？", "その本は読む価値がある。"],
  ["She provided him with practical advice. 日本語訳は？", "彼女は彼に実用的な助言をした。"],
  ["He is said to have invented the device. 日本語訳は？", "彼がその装置を発明したと言われている。"],
  ["The stadium can accommodate fifty thousand people. 日本語訳は？", "そのスタジアムは5万人収容できる。"],
  ["They reached an agreement after negotiations. 日本語訳は？", "交渉の末、合意に達した。"],
  ["He is engaged in environmental research. 日本語訳は？", "彼は環境研究に従事している。"],
  ["The experiment was carried out under strict conditions. 日本語訳は？", "その実験は厳密な条件下で行われた。"],
  ["In spite of the rain, we went out. 日本語訳は？", "雨にもかかわらず、私たちは出かけた。"],
  ["As a result, the sales increased rapidly. 日本語訳は？", "その結果、売上は急増した。"],
  ["On the other hand, the costs also rose. 日本語訳は？", "一方で、費用も増えた。"],
  ["He was able to overcome his fear. 日本語訳は？", "彼は恐怖を克服できた。"],
  ["We should keep in mind that mistakes happen. 日本語訳は？", "間違いは起こりうることを心に留めるべきだ。"],
  ["She is in charge of marketing. 日本語訳は？", "彼女はマーケティング担当だ。"],
  ["I have been involved in the project since the beginning. 日本語訳は？", "私は最初からそのプロジェクトに関わっている。"],
  ["He made an excuse for his absence. 日本語訳は？", "彼は欠席の言い訳をした。"],
  ["The medicine has side effects. 日本語訳は？", "その薬には副作用がある。"],
  ["She burst into tears when she heard the news. 日本語訳は？", "その知らせを聞いて彼女は泣き出した。"],
  ["It took me a while to get used to the new job. 日本語訳は？", "新しい仕事に慣れるのにしばらくかかった。"],
  ["He is accustomed to working under pressure. 日本語訳は？", "彼はプレッシャーの下で働くことに慣れている。"]
];
